### ISSUE TITLE
org.esa.snap.product.library.v2.activator.ProductLibraryActivator: Failed to initialize the database.

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/docker-esa-snap#8]
When running Some S1tbx processes in the image, I get this error/warning (the processing still succeeds):

```
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
SEVERE: org.esa.snap.product.library.v2.activator.ProductLibraryActivator: Failed to initialize the database.
org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:?/.snap/product-library/products;AUTO_SERVER=TRUE". Use an absolute path, ~/name, ./name,
or the baseDir setting instead. [90011-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:388)
        at org.h2.engine.Engine.openSession(Engine.java:50)
        at org.h2.engine.Engine.openSession(Engine.java:179)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
        at org.h2.engine.Engine.createSession(Engine.java:140)
        at org.h2.engine.Engine.createSession(Engine.java:28)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
        at org.h2.Driver.connect(Driver.java:69)
...
```

**Comment by j08lue** [comment]
So some part of SNAP generates this path `?/.snap/product-library/products;AUTO_SERVER=TRUE` and does not like it, duh. Could be that the `?` should be a `~`, such that the link points to the regular user home path `~/.snap`.

This happened first when I was building the docker image as `root`. I tried adding a user with a normal own `HOME` dir, too, to no avail. Might need to make sure that the environment variable is set correctly at runtime.
